# -*- coding: utf-8 -*-
"""Hitorical_VaR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13y8lGkLo7HWMi4SiuZRQfiE4QcUSJYFI
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
from scipy.stats import norm
import yfinance as yf

years = 15
endDate = dt.datetime.now()
startDate = endDate - dt.timedelta(days=365*years)
Tickers = ['SPY', 'BND', 'GLD','QQQ','VTI']

adj_close_df =pd.DataFrame()
for ticker in Tickers:
  data = yf.download(ticker, start=startDate, end=endDate)
  adj_close_df[ticker] = data['Close']

print(adj_close_df)

log_returns = np.log(adj_close_df/adj_close_df.shift(1))
log_returns = log_returns.dropna()

print(log_returns)

Portfolio_value = 100000
weights = np.array([1/len(Tickers)]*len(Tickers))
print(weights)

historical_returns = (log_returns* weights).sum(axis=1)
print(historical_returns)

days = 5
range_returns = historical_returns.rolling(days).sum().dropna()
print(range_returns)

confidence_interval = 0.95
significance_level = 0.05
Var = -np.percentile(range_returns, significance_level*100)*Portfolio_value
print(Var)

return_window = days

range_returns = historical_returns.rolling(return_window).sum().dropna()

range_returns_dollar = range_returns * Portfolio_value

plt.hist(range_returns_dollar, bins=50, density=True)
plt.xlabel(f'{return_window}-Day portfolio return (dollar value)')
plt.ylabel('Frequency')
plt.title(f'Distribution of portfolio {return_window}-day returns')
plt.axvline(-Var, color='r', linestyle='dashed', linewidth=2, label='Value at Risk')
plt.legend()
plt.show()
