# -*- coding: utf-8 -*-
"""Hitorical VaR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13y8lGkLo7HWMi4SiuZRQfiE4QcUSJYFI
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
from scipy.stats import norm
import yfinance as yf

"""# Set time from to a certain number of years"""

years = 15
endDate = dt.datetime.now()
startDate = endDate - dt.timedelta(days=365*years)
Tickers = ['SPY', 'BND', 'GLD','QQQ','VTI']

"""Line-by-line explanation

endDate = dt.datetime.now()
→ This sets endDate to right now (current date & time).

dt.timedelta(days=365 * years)
→ This creates a time span of 15 × 365 days
→ That’s your approximation of 15 years.

startDate = endDate - dt.timedelta(...)
→ Subtracts 15 years’ worth of days from today
→ Result: startDate is the date 15 years ag


"""

adj_close_df =pd.DataFrame()
for ticker in Tickers:
  data = yf.download(ticker, start=startDate, end=endDate)
  adj_close_df[ticker] = data['Close']

print(adj_close_df)

"""#calculate the daily log retruns and drop any NAs"""

log_retruns = np.log(adj_close_df/adj_close_df.shift(1))
log_retruns = log_retruns.dropna()

print(log_retruns)

"""#create and equally weighted portfolio

"""

Portfolio_value = 100000
weights = np.array([1/len(Tickers)]*len(Tickers))
print(weights)

"""#calculate the historical portfolio returns"""

historical_retruns = (log_retruns* weights).sum(axis=1)
print(historical_retruns)

"""#find the x day historical returns"""

days = 5
range_returns = historical_retruns.rolling(days).sum().dropna()
print(range_returns)

"""#specify a confidence internval and calculate the value at risk using historical method"""

confidence_interval = 0.95
significance_level = 0.05
Var = -np.percentile(range_returns, significance_level*100)*Portfolio_value
print(Var)

"""#plot the results of the historical returns"""

return_window = days
# Corrected 'historical_return' to 'historical_retruns'
range_returns = historical_retruns.rolling(return_window).sum().dropna()

range_returns_dollar = range_returns * Portfolio_value

plt.hist(range_returns_dollar, bins=50, density=True)
plt.xlabel(f'{return_window}-Day portfolio return (dollar value)')
plt.ylabel('Frequency')
plt.title(f'Distribution of portfolio {return_window}-day returns')
plt.axvline(-Var, color='r', linestyle='dashed', linewidth=2, label='Value at Risk')
plt.legend()
plt.show()

