# -*- coding: utf-8 -*-
"""Variance - covariance python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcJViflJg4RCk0upZyzSHYIB9p2Z84PV
"""

# VaR
import numpy as np
import pandas as pd
import datetime as dt
import yfinance as yf
import matplotlib.pyplot as plt

years = 15 #Lookback period
endDate = dt.datetime.now()
startDate = endDate - dt.timedelta(days=365*years)

tickers = ['SPY', 'AAPL','TSLA','AMZN','MSFT']

print(endDate)
print(startDate)

adj_close_df = pd.DataFrame()
for ticker in tickers:
  data = yf.download(ticker, start=startDate, end=endDate)
  adj_close_df[ticker] = data[ 'Close']

data = yf.download('SPY', start=startDate, end=endDate)

print(adj_close_df)

print(adj_close_df.shift(1))

print(log_returns)

portfolio_value = 1000000
weights = np.array([1/len(tickers)]* len(tickers))
historical_returns = (log_returns * weights).sum(axis=1)

print(weights)

print(historical_returns)

days = 5
historical_x_days_returns = historical_returns.rolling(days).sum()

print(historical_x_days_returns)

cov_matrix = log_returns.cov() * 252
portfolio_std_dev = np.sqrt(weights.T @ cov_matrix @ weights)

cov_matrix

portfolio_std_dev

from scipy.stats import norm
confidence_level = [0.95,0.99,0.90]
VaRs = []
for confidence_level in confidence_level:
  VaR = portfolio_value * (norm.ppf(1-confidence_level) * portfolio_std_dev * np.sqrt(days / 252) - historical_returns.mean() *days)
  VaRs.append(VaR)

VaRs

import matplotlib.pyplot as plt

# Scale historical 5-day returns by portfolio value
scaled_returns = historical_x_days_returns.dropna() * portfolio_value

# Plot the histogram
plt.figure(figsize=(12, 7))
plt.hist(scaled_returns, bins=100, color='skyblue', edgecolor='black', alpha=0.7)

# Define colors for VaR lines
colors = ['orange', 'red', 'darkred']
labels = ['95% VaR', '99% VaR', '90% VaR'] # Based on order in confidence_level list

# Overlay VaR lines
for var, color, label in zip(VaRs, colors, labels):
    plt.axvline(var, color=color, linestyle='--', linewidth=2, label=f'{label}: ${var:,.2f}')

plt.title(f'Histogram of 5-Day Portfolio Returns (Scaled to ${portfolio_value:,})')
plt.xlabel('Portfolio Change ($)')
plt.ylabel('Frequency')
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.show()